# Generated by Django 4.1 on 2022-08-15 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_provided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tuition',
            name='subject',
            field=models.ManyToManyField(to='tuition.subject'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tution_tutored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.tuition'),
        ),
    ]
