# Generated by Django 4.1 on 2022-08-19 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuition', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tution_tutored', to=settings.AUTH_USER_MODEL),
        ),
    ]
