# Generated by Django 4.1 on 2022-08-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_alter_tuition_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
