# Generated by Django 4.1 on 2022-08-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_tuition_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='current_class',
            new_name='class_name',
        ),
    ]
