# Generated by Django 4.1 on 2022-08-19 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_rename_current_class_level_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
