# Generated by Django 4.1 on 2022-08-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_tuition_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='tuition',
            name='level',
            field=models.CharField(default='all', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tuition',
            name='subject',
            field=models.CharField(default='all', max_length=200),
            preserve_default=False,
        ),
    ]
