# Generated by Django 4.1 on 2022-08-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0007_remove_tuition_tutor_remove_tuition_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
